version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: # allocate from https://console.curseforge.com/
      CF_SLUG: vault-hunters-1-18-2
      CF_FILENAME_MATCHER: "Update-6H"
      MEMORY: 4G
    volumes:
      - mc-data:/data

volumes:
  mc-data: {}